### ISSUE TITLE
Globals as opt-in?

### ISSUE THREAD

**Issue by wejendorp** [Tradeshift/eslint-config-tradeshift#7]
Maybe we can create a nested config, specifically for V4-apps / frontend.
I just had a big mistake slip because of the `server` global being allowed (but not existing in scope).

@sqren @sampi thoughts?

**Comment by sqren** [comment]
These are the current globals:
```
	"globals": {
		"t": true,
		"ts": true,
		"gui": true,
		"app": true,
		"__app": true,
		"__config": true,
		"runtime": true,
		"server": true
	},
```
They are specific to Apps/Apps-Server so should not be in the shared config.
Eg. Collaboration-Backend doesn't have any of those globals, and will never have them.

The same with the `env`:
```
"es6": true,
"browser": true,
"node": true,
"jasmine": true
```

We can not assume that every project will be a browser + node project using jasmine. It could be a node-only project using Mocha. 

My suggestion: remove the `env` and `globals` entirely from the shared, and let the project specific configs deal with this.

**Comment by wejendorp** [comment]
I totally agree. Let's strip it down so it's only about style. Not .. implementation details.

**Comment by sampi** [comment]
sounds good to me, wanna make a PR? I see this https://github.com/Tradeshift/eslint-config-tradeshift/pull/9 but I don't see the actual changes inside of it

**Comment by sqren** [comment]
The actual change was in https://github.com/Tradeshift/eslint-config-tradeshift/pull/8

**Comment by wejendorp** [comment]
#8 has been merged and apps/apps-server have been migrated.
#9 has been pushed to npm but is borked.
